In [1]:
import numpy as np

In [10]:
arr1 = np.array([])
print(arr1.shape)
arr1 = arr1[np.newaxis]
print(arr1.shape)

(0,)
(1, 0)


In [13]:
arr2 = np.arange(3)
print(arr2.shape)
arr2 = arr2[np.newaxis]
print(arr2.shape)

(3,)
(1, 3)


In [14]:
arr3 = np.arange(3)
print(arr2.shape)
arr3 = arr3[:, np.newaxis]
print(arr3.shape)

(1, 3)
(3, 1)


In [20]:
arr4 = np.arange(6).reshape(3, 2)
print(arr4.shape)
arr4 = arr4[:, :, np.newaxis]
print(arr4.shape)

(3, 2)
(3, 2, 1)


In [35]:
arr5 = np.arange(6).reshape(3, 2)
print(arr5.shape)
arr5 = arr5[:, np.newaxis, :]
print(arr5.shape)

(3, 2)
(3, 1, 2)


In [38]:
arr6 = np.arange(6).reshape(3, 2)
print(arr6.shape)
arr6 = arr6[np.newaxis, :, :]
print(arr6.shape)

(3, 2)
(1, 3, 2)


In [43]:
arr7 = np.arange(120).reshape(1, 3, 1, 4, 2, 5, 1, 1)
print(arr7.shape)
arr7 = arr7.reshape(3, 4, 2, 5)
print(arr7.shape)

(1, 3, 1, 4, 2, 5, 1, 1)
(3, 4, 2, 5)


In [56]:
arr8 = np.arange(24).reshape(4, 6)
print(arr8.shape)
arr8_ravel = arr8.ravel()
print(arr8_ravel.shape)
arr8_flatten = arr8.flatten()
print(arr8_flatten.shape)
arr8_reshape = arr8.reshape(24)
print(arr8_reshape.shape)
arr8 = arr8.reshape(4, 2, 3)
print(arr8.shape)
arr8 = arr8.reshape(6, 2, 2)
print(arr8.shape)

(4, 6)
(24,)
(24,)
(24,)
(4, 2, 3)
(6, 2, 2)


In [79]:
arr9 = np.arange(120).reshape(2, 3, 4, 5)
print(arr9.shape)
arr9_permuted = arr9.reshape(2, 5, 3, 4)
print(arr9_permuted.shape)
arr9 = arr9.reshape(1, 1, -1, 2)
print(arr9.shape)

(2, 3, 4, 5)
(2, 5, 3, 4)
(1, 1, 60, 2)


In [88]:
arr10 = np.arange(20).reshape(4, 5)
print(arr10.shape)
arr10 = arr10.swapaxes(1, 0)
print(arr10.shape)

(4, 5)
(5, 4)


In [105]:
np.random.seed(37)

arr11 = np.random.randint(1, 21, 5)
arr12 = np.random.randint(1, 21, 5)
arr13 = np.random.randint(1, 21, 5)
arr14 = np.concatenate((arr11, arr12, arr13))
arr14 = arr14.reshape(3, 5)
arr15 = np.sort(arr14, axis = 1)
print(arr15)

[[ 4  4 12 13 16]
 [ 4  9  9 11 19]
 [13 13 15 18 20]]


In [143]:
np.random.seed(15)

N = 6
H = 3
W = 4
C = 5

x = np.empty(shape = (0, H, W, C))

for n in range(N):
  new_image = np.random.randint(1, 100, (H, W, C))
  x = np.concat(new_image, axis = 0)

In [126]:
np.random.seed(423)

x_list = []

for n in range(N):
  new_image = np.random.randint(1, 100, (H, W, C))
  x_list.append(new_image)

x_array = np.concatenate(x_list, axis = 0)

In [147]:
intercept_ = np.array([])
d = 10
coef_ = np.arange(d)
theta = np.arange(d + 1)
theta_concat = np.concat((intercept_, coef_))
theta_stack = np.hstack((intercept_, coef_))

In [179]:
N = 3
d = 2
X = np.arange(N * d).reshape(N, d)
y = np.ones((N, 1))
X = np.hstack((y, X))
print(X)


[[0 1]
 [2 3]
 [4 5]]
[[1.]
 [1.]
 [1.]]
(3, 1)
[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]]
