In [ ]:
import numpy as np

N = 5
x = np.arange(N)
y = np.arange(N)

dot_product = x @ y
print(dot_product)
print(dot_product.shape)

# x @ y compute the dot product of x and y and the shape returned is 0

30
()


In [ ]:
x = np.arange(N)
y = np.arange(N * N).reshape(N, N)

dot_product = x @ y
print(dot_product)
print(dot_product.shape)

# x @ y works only if the shape of x is equal to the rows of y and the shape returned is N,

[150 160 170 180 190]
(5,)


In [ ]:
x = np.arange(N)
y = np.arange(N * N).reshape(N, N)

dot_product = y @ x
print(dot_product)
print(dot_product.shape)

# y @ x works only if the shape of x is equal to the columns of y and the shape returned is N,

[ 30  80 130 180 230]
(5,)


In [ ]:
M = 3

x = np.arange(N * M).reshape(N, M)
y = np.arange(N * M).reshape(M, N)

dot_product = x @ y
print(dot_product)
print(dot_product.shape)

# the requirement is that the cols of x = rows of y.
# the shape will be (rows of x, cols of y)

[[ 25  28  31  34  37]
 [ 70  82  94 106 118]
 [115 136 157 178 199]
 [160 190 220 250 280]
 [205 244 283 322 361]]
(5, 5)


In [ ]:
x = np.arange(6)
diag = np.diag(x)
print(diag)
print(diag.shape)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
(6, 6)


In [ ]:
identity = np.identity(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
np.random.seed(14)

x = np.random.randn(5, 5)
print(x)
print()

x_row_index = np.arange(5).reshape(5, 1)
x_col_index = np.arange(5)
y = x_row_index <= x_col_index
print(y)
print()

x[y] = -np.inf
print(x)

[[ 1.55133911  0.07918602  0.17397653 -0.07233657 -2.0043294 ]
 [ 0.14467781 -1.50116862  0.21110945 -0.55820506  1.08452906]
 [-0.18628912  0.01466137 -1.07556947  0.64225207 -0.18033671]
 [ 0.62030025  0.81097433  0.77793587 -0.23748968 -1.89191235]
 [-1.17212179  0.83620697  1.0092734   1.29309936 -0.54933117]]

[[ True  True  True  True  True]
 [False  True  True  True  True]
 [False False  True  True  True]
 [False False False  True  True]
 [False False False False  True]]

[[       -inf        -inf        -inf        -inf        -inf]
 [ 0.14467781        -inf        -inf        -inf        -inf]
 [-0.18628912  0.01466137        -inf        -inf        -inf]
 [ 0.62030025  0.81097433  0.77793587        -inf        -inf]
 [-1.17212179  0.83620697  1.0092734   1.29309936        -inf]]


In [ ]:
x = np.arange(9).reshape(3, 3)
Q, R = np.linalg.qr(x)
print(Q)
print()
print(R)

[[ 0.          0.91287093  0.40824829]
 [-0.4472136   0.36514837 -0.81649658]
 [-0.89442719 -0.18257419  0.40824829]]

[[-6.70820393e+00 -8.04984472e+00 -9.39148551e+00]
 [ 0.00000000e+00  1.09544512e+00  2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [ ]:
U, S, Vt = np.linalg.svd(x)
print(U)
print()
print(S)
print()
print(Vt)
print()

reconstructed = U @ np.diag(S) @ Vt
print(reconstructed)

[[-0.13511895  0.90281571  0.40824829]
 [-0.49633514  0.29493179 -0.81649658]
 [-0.85755134 -0.31295213  0.40824829]]

[1.42267074e+01 1.26522599e+00 5.89938022e-16]

[[-0.4663281  -0.57099079 -0.67565348]
 [-0.78477477 -0.08545673  0.61386131]
 [-0.40824829  0.81649658 -0.40824829]]

[[-1.14123474e-16  1.00000000e+00  2.00000000e+00]
 [ 3.00000000e+00  4.00000000e+00  5.00000000e+00]
 [ 6.00000000e+00  7.00000000e+00  8.00000000e+00]]


In [ ]:
x = np.arange(25).reshape(5, 5)

det = np.linalg.det(x)
print(det)
print()

trace = np.linalg.trace(x)
print(trace)
print()

vals, vec = np.linalg.eig(x)
print(vals)
print()
print(vec)

0.0

60

[ 6.39116499e+01+0.00000000e+00j -3.91164992e+00+0.00000000e+00j
 -3.22069971e-15+0.00000000e+00j  2.58587115e-16+7.36422729e-16j
  2.58587115e-16-7.36422729e-16j]

[[-0.0851802 +0.j          0.67779864+0.j          0.24109755+0.j
   0.23152795-0.12469177j  0.23152795+0.12469177j]
 [-0.23825372+0.j          0.36348873+0.j         -0.54061326+0.j
  -0.21054131-0.10215471j -0.21054131+0.10215471j]
 [-0.39132723+0.j          0.04917881+0.j         -0.02551006+0.j
   0.18426328+0.4026156j   0.18426328-0.4026156j ]
 [-0.54440074+0.j         -0.2651311 +0.j          0.70846967+0.j
  -0.66301443+0.j         -0.66301443-0.j        ]
 [-0.69747425+0.j         -0.57944101+0.j         -0.38344391+0.j
   0.45776451-0.17576912j  0.45776451+0.17576912j]]


In [ ]:
np.random.seed(15)

A = np.random.randint(0, 11, (4, 4))
inverse = np.linalg.inv(A)
# no error = invertible!

x = np.random.randint(0, 11, 4)
sol = np.linalg.solve(A, b)
print(sol)
print()

print(A @ sol)
print(b) # sol and b match up

[-0.65867769 -0.51983471  0.45206612  1.22975207]

[3. 6. 8. 2.]
[3 6 8 2]


In [ ]:
np.random.seed(57)

M = np.random.randint(0, 6, (5, 5))

det = np.linalg.det(M)
print(det)
print()

rank = np.linalg.matrix_rank(M)
print(rank)
print()

trace = np.linalg.trace(M)
print(trace)
print()

inverse = np.linalg.inv(A)
print(inverse)
print()

print(A @ inverse) # approximately identity matrix

-1344.0000000000002

5

16

[[ 0.06528926 -0.2214876   0.03140496  0.11157025]
 [-0.17933884 -0.27768595  0.12892562  0.32644628]
 [ 0.10826446  0.32892562 -0.18842975 -0.16942149]
 [ 0.11900826  0.21652893  0.00661157 -0.23966942]]

[[ 1.00000000e+00  1.11022302e-16  6.67868538e-17  1.38777878e-16]
 [ 2.77555756e-17  1.00000000e+00 -1.09287579e-16  2.77555756e-16]
 [ 1.94289029e-16  2.22044605e-16  1.00000000e+00 -5.55111512e-17]
 [ 9.71445147e-17  1.11022302e-16 -6.33174069e-17  1.00000000e+00]]


In [ ]:
np.random.seed(27)

E = np.random.randint(0, 6, (3, 3))
vals, vec = np.linalg.eig(E)
print(vals)
print()
print(vec)
print()

for i in range(len(vals)):
  Av = E @ vec[:, i]
  lambdav = vals[i] * vec[:, i]
  print(np.allclose(Av, lambdav))

[ 5.85410197 -0.85410197  3.        ]

[[ 0.          0.          1.        ]
 [ 0.6494574   0.98572192  0.        ]
 [ 0.76039797 -0.16838141  0.        ]]

True
True
True


In [ ]:
A = np.random.randint(0, 11, (4, 4))
B = np.random.randint(0, 11, (4, 4))

C = A @ B
print(C)
print()

det = np.linalg.det(C)
print(det)
trace = np.linalg.trace(C)
print(trace)
rank = np.linalg.matrix_rank(C)
print(rank)
inverse = np.linalg.inv(C)
print(inverse)
print() # C is invertible!

b = np.random.randint(0, 11, 4)
sol = np.linalg.solve(C, b)
print(sol)
print()

Q, R = np.linalg.qr(C)
print(Q)
print(R)
print()

U, S, Vt = np.linalg.svd(C)
print(U)
print(S)
print(Vt)

[[ 79  56  57  26]
 [ 70  61  61  22]
 [130  72  74  54]
 [ 92  63  65  46]]

-22535.999999999873
260
4
[[ 0.0257366  -0.01499823  0.03159389 -0.04446219]
 [-1.46556621  1.03682996  0.57330493 -0.34052183]
 [ 1.49006035 -1.02351793 -0.61909833  0.37406816]
 [-0.14980476  0.05626553  0.02644657  0.0484558 ]]

[-0.21538871  3.43423855 -3.34957401  0.67784878]

[[-0.41347658 -0.21204135  0.03009637 -0.88496881]
 [-0.36637165 -0.73797356 -0.45900473  0.33238757]
 [-0.6804045   0.62519955 -0.34895071  0.15623265]
 [-0.48151703 -0.13985354  0.81648164  0.28625176]]
[[-191.0628169  -124.82805596 -127.5653756   -77.70219366]
 [   0.          -20.68710817  -19.9284575     5.57901946]
 [   0.            0.            0.96515822    9.39921837]
 [   0.            0.            0.            5.90748136]]

[[-0.42098097 -0.28844633  0.39063722  0.76614379]
 [-0.40918034 -0.73814647  0.05949554 -0.53307741]
 [-0.63633629  0.60500005  0.3659314  -0.30845627]
 [-0.50042242  0.07689892 -0.84258949  0.18