In [6]:
import pandas as pd
import numpy as np

s = pd.Series([1, 2, 3, 4, 5], index = ['a', 'b', 'c', 'd', 'e'], dtype = np.float64)
print(s)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64


In [10]:
dictionary = {
    "dogs": 3,
    "cats": 1,
    "bunnies": 7,
    "turtles": 2,
    "fish": 11
}

dict_series = pd.Series(dictionary)
print(dict_series)

dogs        3
cats        1
bunnies     7
turtles     2
fish       11
dtype: int64


In [14]:
arr = np.arange(5)
np_series = pd.Series(arr)
print(np_series)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [18]:
empty_series = pd.Series(dtype = np.bool)
print(empty_series)

Series([], dtype: bool)


In [39]:
dict_lists = {
    'Col 1': [0, 1, 2, 4, 5],
    'Col 2': [6, 7, 8, 9, 10],
    'Col 3': [11, 12, 13, 14, 15],
}

df_dict_lists = pd.DataFrame(dict_lists)
print(df_dict_lists)

   Col 1  Col 2  Col 3
0      0      6     11
1      1      7     12
2      2      8     13
3      4      9     14
4      5     10     15


In [45]:
dict_series = {
    "Series 1": pd.Series([0, 1, 2, 3, 4]),
    "Series 2": pd.Series([6, 7, 8, 9, 10]),
    "Series 3": pd.Series([11, 12, 13, 14, 15]),
}

df_dict_series = pd.DataFrame(dict_series)
print(df_dict_series)

   Series 1  Series 2  Series 3
0         0         6        11
1         1         7        12
2         2         8        13
3         3         9        14
4         4        10        15


In [64]:
np.random.seed(10)

dict1 = {
    '1': np.random.randint(1, 101, 5),
    '2': np.random.randint(1, 101, 5),
    '3': np.random.randint(1, 101, 5),
}

dict2 = {
    '1': np.random.randint(1, 101, 5),
    '2': np.random.randint(1, 101, 5),
    '3': np.random.randint(1, 101, 5),
}

dict3 = {
    '1': np.random.randint(1, 101, 5),
    '2': np.random.randint(1, 101, 5),
    '3': np.random.randint(1, 101, 5),
}

dict4 = {
    '1': np.random.randint(1, 101, 5),
    '2': np.random.randint(1, 101, 5),
    '3': np.random.randint(1, 101, 5),
}

dict5 = {
    '1': np.random.randint(1, 101, 5),
    '2': np.random.randint(1, 101, 5),
    '3': np.random.randint(1, 101, 5),
}

list_dicts = list([dict1, dict2, dict3, dict4, dict5])
df_list_dicts = pd.DataFrame(list_dicts)
print(df_list_dicts)

                      1                     2                     3
0  [10, 16, 65, 29, 90]    [94, 30, 9, 74, 1]  [41, 37, 17, 12, 55]
1  [89, 63, 34, 73, 79]  [50, 52, 55, 78, 70]  [14, 26, 14, 93, 87]
2  [31, 31, 90, 13, 66]  [32, 58, 37, 28, 19]  [94, 78, 23, 24, 95]
3  [12, 29, 75, 89, 10]  [16, 19, 81, 72, 89]   [12, 18, 47, 8, 76]
4  [29, 34, 85, 97, 89]    [45, 6, 5, 72, 89]  [89, 51, 55, 35, 16]


In [73]:
arr_2d = np.arange(15).reshape(5, 3)

df_arr_2d = pd.DataFrame(arr_2d, index = ["A", "B", "C", "D", "E"], columns = ["A", "B", "C"])
print(df_arr_2d)

    A   B   C
A   0   1   2
B   3   4   5
C   6   7   8
D   9  10  11
E  12  13  14


In [77]:
series = pd.Series([0, 1, 2, 3, 4])
series_arr = np.array(series)
print(series_arr)

[0 1 2 3 4]


In [84]:
dataframe = pd.DataFrame({'A': [10, 20, 30, 60, 70], 'B': [40, 50, 60, 70, 80], 'C': [1, 2, 3, 4, 5]})
dataframe_arr = np.array(dataframe)
print(dataframe_arr)

[[10 40  1]
 [20 50  2]
 [30 60  3]
 [60 70  4]
 [70 80  5]]


In [88]:
empty_dataframe = pd.DataFrame(dtype = np.float64)
print(empty_dataframe)

Empty DataFrame
Columns: []
Index: []
